# This workflow will install Python dependencies,
# run tests with a variety of Python versions,
# and upload a new build to TestPyPI.
#
# For more information see:
# https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Unit tests

on:
  push:
    branches-ignore:
      - 'dependabot/**'  # Avoid duplicates; only run the PR, not the push
      - 'gh-pages'  # GitHub Pages do not trigger all tests
    tags-ignore:
      - 'v*'  # Avoid re-running existing commit on release
  pull_request:
    branches:
      - 'main'

permissions:
  id-token: write
  contents: read

concurrency:
  group: check-${{ github.ref }}
  cancel-in-progress: true

env:
  FORCE_COLOR: 1

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python-version: [
          '3.10',
          '3.11',
          '3.12',
          '3.13',
        ]

    env:
      PYTHON_VERSION: ${{ matrix.python-version }}

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        cache-dependency-glob: "uv.lock"
        enable-cache: true
        python-version: ${{ matrix.python-version }}

    - name: Add .local/bin to Windows PATH
      if: runner.os == 'Windows'
      shell: bash
      run: echo "$USERPROFILE/.local/bin" >> $GITHUB_PATH

    - name: Install tox
      run: uv tool install --python-preference only-managed --python 3.13 tox --with tox-uv --with tox-gh

    - name: Install Python
      if: matrix.python-version != '3.13'
      run: uv python install --python-preference only-managed ${{ matrix.python-version }}

    - name: Setup test suite
      run: tox run -vv --notest --skip-missing-interpreters false
      env:
        TOX_GH_MAJOR_MINOR: ${{ matrix.python-version }}

    - name: Run test suite
      run: tox run -vv --skip-pkg-install
      env:
        TOX_GH_MAJOR_MINOR: ${{ matrix.python-version }}

    - name: Upload Results to CodeCov
      if: success()
      uses: codecov/codecov-action@v5
      with:
        env_vars: TOXENV
        fail_ci_if_error: false
        files: ./tests/reports/coverage-html/index.html,./tests/reports/coverage.xml
        flags: unittests
        name: ${{ matrix.os }} - Python ${{ matrix.python-version }}
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Upload test results to Codecov
      if: ${{ !cancelled() }}
      uses: codecov/test-results-action@v1
      with:
        directory: ./tests/reports/
        flags: unittests
        name: ${{ matrix.os }} - Python ${{ matrix.python-version }}
        token: ${{ secrets.CODECOV_TOKEN }}


  testpypi-deploy:
    name: Build and publish Python 🐍 distributions 📦 to TestPyPI
    runs-on: ubuntu-latest
    needs: test
    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        cache-dependency-glob: "uv.lock"
        enable-cache: true

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version-file: "pyproject.toml"

    - name: Build
      run: uv build

    - name: Publish distribution 📦 to Test PyPI
      continue-on-error: true
      run: uv publish --token ${{ secrets.PYPI_PASSWORD }} --index testpypi --publish-url https://test.pypi.org/legacy/
